export const meta = {
  name: "dep-audit",
  description: "Audit project dependencies for vulnerabilities, outdated packages, and license issues",
}

export default async function depAudit(args, { agent, parallel, readFile }) {
  const packageManager = args.package_manager || "npm"

  phase("Detect dependencies")
  const deps = await agent(
    `Detect the package manager and list all dependencies.
    For npm: read package.json
    For pip: read requirements.txt or pyproject.toml
    For bun: read package.json
    Return: the dependency list with versions.`,
    { agentType: "explore" }
  )

  phase("Parallel audits")
  const [vulnerabilities, outdated, licenses] = await parallel([
    agent(
      `Check for known vulnerabilities.
      Run: npm audit --json (or equivalent)
      Report: each vulnerability with severity, package, and fix availability.`,
      { agentType: "general" }
    ),
    agent(
      `Check for outdated packages.
      Run: npm outdated --json (or equivalent)
      Report: packages with available updates, grouped by major/minor/patch.`,
      { agentType: "general" }
    ),
    agent(
      `Check dependency licenses.
      Run: license-checker --json (or equivalent)
      Report: any copyleft licenses (GPL, AGPL, etc.) or licenses that may cause legal issues.`,
      { agentType: "general" }
    ),
  ])

  phase("Write report")
  const report = `# Dependency Audit Report

## Vulnerabilities
${vulnerabilities}

## Outdated Packages
${outdated}

## License Issues
${licenses}

---
Generated by dep-audit workflow`

  await writeFile("dep-audit-report.md", report)
  log("Report written to dep-audit-report.md")
  
  return report
}
