export const meta = {
  name: "full-audit",
  description: "Comprehensive project audit: security, performance, code quality, dependencies, and documentation",
}

export default async function fullAudit(args, { agent, parallel, writeFile }) {
  const targetDir = args.dir || "."

  phase("Gather project info")
  const projectInfo = await agent(
    `Analyze the project at ${targetDir}. Return: language, framework, package manager, directory structure, and any config files found.`,
    { agentType: "explore" }
  )

  phase("Parallel audits")
  const [security, performance, quality, deps, docs] = await parallel([
    agent(
      `Security audit of ${targetDir}. Check for: injection vulnerabilities, hardcoded secrets, insecure dependencies, missing auth checks, XSS vectors, SQL injection.`,
      { agentType: "general" }
    ),
    agent(
      `Performance audit of ${targetDir}. Check for: N+1 queries, missing indexes, unnecessary re-renders, large bundle sizes, blocking operations, memory leaks.`,
      { agentType: "general" }
    ),
    agent(
      `Code quality audit of ${targetDir}. Check for: dead code, duplication, complexity, naming, error handling, test coverage, type safety.`,
      { agentType: "general" }
    ),
    agent(
      `Dependency audit of ${targetDir}. Check for: outdated packages, known vulnerabilities, unused dependencies, license issues, missing lock file.`,
      { agentType: "general" }
    ),
    agent(
      `Documentation audit of ${targetDir}. Check for: missing README, outdated docs, missing API docs, missing inline comments for complex logic.`,
      { agentType: "general" }
    ),
  ])

  phase("Compile report")
  const report = `# Full Project Audit Report

## Project Info
${projectInfo}

## Security
${security}

## Performance
${performance}

## Code Quality
${quality}

## Dependencies
${deps}

## Documentation
${docs}

---
Generated by full-audit workflow at ${new Date().toISOString()}`

  await writeFile("full-audit-report.md", report)
  log("Report written to full-audit-report.md")
  
  return report
}
