export const meta = {
  name: "pr-review",
  description: "Automated PR review workflow: fetch PR, analyze changes, check for issues, post review",
}

export default async function prReview(args, { agent, parallel, readFile, writeFile }) {
  const prNumber = args.pr_number || args
  const repo = args.repo || "."

  // Phase 1: Gather PR info
  phase("Fetch PR details")
  const prInfo = await agent(
    `Run: gh pr view ${prNumber} --repo ${repo} --json title,body,additions,deletions,changedFiles,headRefName,baseRefName
    Return the full JSON output.`,
    { agentType: "explore" }
  )

  // Phase 2: Get diff
  phase("Get diff")
  const diff = await agent(
    `Run: gh pr diff ${prNumber} --repo ${repo}
    Return the full diff output.`,
    { agentType: "explore" }
  )

  // Phase 3: Parallel analysis
  phase("Analyze changes")
  const [securityReview, codeQuality, testCoverage] = await parallel([
    agent(
      `Review this diff for security vulnerabilities (OWASP Top 10, injection, auth, secrets, XSS).
      Diff:\n${diff}\n
      Report: list each issue with severity (critical/high/medium/low), file:line, and suggestion.`,
      { agentType: "general" }
    ),
    agent(
      `Review this diff for code quality issues (dead code, complexity, naming, duplication, error handling).
      Diff:\n${diff}\n
      Report: list each issue with severity and suggestion.`,
      { agentType: "general" }
    ),
    agent(
      `Check if this diff has adequate test coverage. List any new functions/branches without tests.
      Diff:\n${diff}\n
      Report: what's tested, what's missing, and suggest test cases.`,
      { agentType: "general" }
    ),
  ])

  // Phase 4: Write report
  phase("Write review report")
  const report = `# PR #${prNumber} Review Report

## Security Review
${securityReview}

## Code Quality
${codeQuality}

## Test Coverage
${testCoverage}

---
Generated by pr-review workflow`
  
  await writeFile(`pr-${prNumber}-review.md`, report)
  log(`Review written to pr-${prNumber}-review.md`)
  
  return report
}
